name: ðŸš€ Auto Deploy to Server

on:
  push:
    branches:
      - main   # Ganti sesuai branch utama kamu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install expect
      run: sudo apt-get update && sudo apt-get install -y expect

    - name: Setup SSH connection
      run: |
        eval "$(ssh-agent -s)"
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | expect -c "
        spawn ssh-add "${{ secrets.SERVER_USER }}"
        expect \"Enter passphrase for*\"
        send \"${{ secrets.SSH_PASSPHRASE }}\r\"
        expect eof
        "

    - name: Add server to known hostss
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to server via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
          cd htdocs/hosting.kotaciamis.com/billing/ || exit 1
          git pull origin main
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan migrate --force
          php artisan optimize:clear
          npm install
          npm run build
        "
