name: ðŸš€ Auto Deploy to Server

on:
  push:
    branches:
      - main   # Ganti sesuai branch utama kamu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install expect
      run: sudo apt-get update && sudo apt-get install -y expect

    - name: Setup SSH connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/${{ secrets.SSH_USER}}
        chmod 600 ~/.ssh/${{ secrets.SSH_USER}}
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
        # Test SSH connection
        eval "$(ssh-agent -s)"
        expect << 'EOF'
        spawn ssh-add ~/.ssh/${{ secrets.SSH_USER}}
        expect "Enter passphrase for*"
        send "${{ secrets.SSH_PASSPHRASE }}\r"
        expect eof
        EOF

    - name: Deploy to server via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/${{ secrets.SSH_USER}} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
          cd htdocs/hosting.kotaciamis.com/billing/ || exit 1
          git pull origin main
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          npm ci --production
          npm run build
        "
